Happyr\NormalDistributionBundle\Entity\Fragment:
    type: entity
    table: HappyrDistributionFragment
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    manyToOne:
        summary:
          targetEntity: Happyr\NormalDistributionBundle\Entity\Summary
    fields:
        value:
            type: float
        frequency:
            type: integer
        cumulativeFrequency:
            type: integer
