Happyr\NormalDistributionBundle\Entity\Summary:
    type: entity
    table: HappyrDistributionSummary
    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        name:
            type: string
        population:
            type: integer
