parameters:
  happyr.normal_distribution.normal_distribution_calculator.class: HappyR\NormalDistributionBundle\Services\NormalDistributionCalculator
  happyr.normal_distribution.statistics_service.class: HappyR\NormalDistributionBundle\Services\StatisticsService
  happyr.normal_distribution.distribution_service.class: HappyR\NormalDistributionBundle\Services\DistributionService

services:
  happyr.normal_distribution.normal_distribution_calculator:
    class: %happyr.normal_distribution.normal_distribution_calculator.class%
    arguments: []

  happyr.normal_distribution.statistics_service:
    class: %happyr.normal_distribution.statistics_service.class%
    arguments: []

  happyr.normal_distribution.distribution_service:
      class: %happyr.normal_distribution.distribution_service.class%
      arguments: [@doctrine.orm.entity_manager]