parameters:

services:
  Happyr\NormalDistributionBundle\Service\Calculator:
    class: Happyr\NormalDistributionBundle\Service\Calculator
    arguments: []

  Happyr\NormalDistributionBundle\Service\StatisticsHelper:
    class: Happyr\NormalDistributionBundle\Service\StatisticsHelper
    arguments: []

  Happyr\NormalDistributionBundle\Service\DistributionManager:
      class: Happyr\NormalDistributionBundle\Service\DistributionManager
      arguments: ["@doctrine.orm.entity_manager"]
