parameters:

services:
  happyr.normal_distribution.normal_distribution_calculator:
    class: Happyr\NormalDistributionBundle\Service\NormalDistributionCalculator
    arguments: []

  happyr.normal_distribution.statistics_service:
    class: Happyr\NormalDistributionBundle\Service\StatisticsService
    arguments: []

  happyr.normal_distribution.distribution_service:
      class: Happyr\NormalDistributionBundle\Service\DistributionService
      arguments: [@doctrine.orm.entity_manager]