parameters:
  happyr.normal_distirbution.normal_distirbution_service.class: HappyR\NormalDistributionBundle\Services\NormalDistributionService

services:
  happyr.normal_distirbution.normal_distirbution_service:
    class: %happyr.normal_distirbution.normal_distirbution_service.class%
    arguments: []

