parameters:

services:
  Happyr\NormalDistributionBundle\Service\NormalDistributionCalculator:
    class: Happyr\NormalDistributionBundle\Service\NormalDistributionCalculator
    arguments: []

  Happyr\NormalDistributionBundle\Service\StatisticsService:
    class: Happyr\NormalDistributionBundle\Service\StatisticsService
    arguments: []

  Happyr\NormalDistributionBundle\Service\DistributionService:
      class: Happyr\NormalDistributionBundle\Service\DistributionService
      arguments: ["@doctrine.orm.entity_manager"]
