language: php

php:
    - 7.0
    - 7.1

env:
  global:
    - TEST_COMMAND="composer test"
  matrix:
    - SYMFONY_VERSION=3.3.*
    - SYMFONY_VERSION=2.7.*

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_VERSION=2.7.* TEST_COMMAND="composer test-ci"

install:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - $TEST_COMMAND