parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Happyr\NormalDistributionBundle\Service\Calculator: ~
    Happyr\NormalDistributionBundle\Service\StatisticsHelper: ~
    Happyr\NormalDistributionBundle\Service\DistributionManager: ~

    Happyr\NormalDistributionBundle\Repository\SummaryRepository: ~
    Happyr\NormalDistributionBundle\Repository\FragmentRepository: ~
